package com.nds.gadai.validators;

import com.nds.gadai.exceptions.ClientException;

public class FixedInstallmentValidator {

    public void nullCheckTransactionNumber(String id) throws ClientException {
        if (id == null) {
            throw new ClientException("Transaction Number is required");
        }
    }

    public void notTransactionNumber(String id) throws ClientException {
        if (id != null) {
            throw new ClientException("Product id is autogenerated, do not input id");
        }
    }

    public void nullCheckObject(Object o) throws ClientException {
        if (o == null) {
            throw new ClientException("Transaction not found");
        }
    }

    public void validateTransactionNumber(String id) throws ClientException {
        if (!id.matches("(\\d+){11}")) {
            throw new ClientException("Transaction number consists of all digit and is 11 digits long");
        }
    }
    
}
